services:
  database:
    image: 'postgres:15.6'
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

volumes:
  database:
